# Generated by Django 6.0.7 on 2026-07-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('departement', models.CharField(choices=[('04', 'Alpes-de-Haute-Provence (04)'), ('05', 'Hautes-Alpes (05)')], max_length=2)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('SALLE', 'Tir en Salle'), ('FEDERAL', "Tir Fédéral (Tir à l'Extérieur)"), ('CAMPAGNE', 'Tir de Campagne'), ('NATURE', 'Tir Nature'), ('3D', 'Tir 3D'), ('BEURSAULT', 'Tir Beursault'), ('RUN', 'Run Archery')], max_length=10, unique=True)),
                ('edition', models.PositiveIntegerField(default=2026)),
                ('date', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('F', 'Fille / Femme'), ('H', 'Garçon / Homme')], max_length=1)),
                ('categorie_age', models.CharField(choices=[('U11', 'U11'), ('U13', 'U13'), ('U15', 'U15'), ('U18', 'U18')], max_length=3)),
                ('type_arc', models.CharField(choices=[('NU', 'Arc Nu (Barebow)'), ('VISEUR', 'Arc avec Viseur (Classique / Poulies)')], max_length=6)),
                ('licence_a_jour', models.BooleanField(default=True, help_text="Doit être coché pour que l'archer soit éligible (Article 2).")),
                ('numero_licence', models.CharField(blank=True, max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archers', to='challenge.club')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text="Score obtenu par l'archer sur cette épreuve. Le classement et les points sont calculés automatiquement, il n'y a pas besoin de saisir une place.")),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='challenge.archer')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='challenge.epreuve')),
            ],
            options={
                'ordering': ['epreuve', '-score'],
                'unique_together': {('archer', 'epreuve')},
            },
        ),
    ]
