# Generated by Django 6.1 on 2026-08-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du club (facultatif), affiché sur le classement des clubs.', null=True, upload_to='clubs/'),
        ),
    ]
